/**
 * Source and licence metadata for booking ship photography.
 *
 * Exact-vessel rule: only publish when verifiedExactShip is true AND
 * source/licence fields are filled. Sister ships and unverified files
 * must never be assigned silently.
 *
 * Synced from data/ship-images/wikimedia-inbox/*.meta.json after import.
 */

export type ShipImageMetadata = {
  shipName: string;
  cruiseLine: string;
  slug: string;
  file: string;
  sourceName: string;
  sourcePage: string;
  author: string;
  licence: string;
  attributionRequired: boolean;
  attributionText: string;
  verifiedExactShip: boolean;
  imagePosition: string;
  internalNotes?: string;
};

export const shipImageMetadataCatalog: readonly ShipImageMetadata[] = [
  {
    shipName: "Azamara Journey",
    cruiseLine: "Azamara",
    slug: "azamara-journey",
    file: "azamara-journey-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Azamara_Journey_closing_in_to_dock.jpg",
    author: "Szilas",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Szilas / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Azamara Onward",
    cruiseLine: "Azamara",
    slug: "azamara-onward",
    file: "azamara-onward-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Azamara_Onward_Basseterre_20251207_1.jpg",
    author: "Z thomas",
    licence: "CC BY 4.0",
    attributionRequired: true,
    attributionText: "Z thomas / Wikimedia Commons / CC BY 4.0",
    verifiedExactShip: true,
    imagePosition: "center 42%",
  },
  {
    shipName: "Azamara Quest",
    cruiseLine: "Azamara Cruises",
    slug: "azamara-quest",
    file: "azamara-quest-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Azamara_Quest_arriving_Tallinn_28_June_2015.JPG",
    author: "Pjotr Mahhonin",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Pjotr Mahhonin / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 42%",
  },
  {
    shipName: "Brilliance Of The Seas",
    cruiseLine: "Royal Caribbean",
    slug: "brilliance-of-the-seas",
    file: "brilliance-of-the-seas-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Brilliance_of_the_Seas_departing_Sydney.jpg",
    author: "Dicklyon",
    licence: "CC BY 4.0",
    attributionRequired: true,
    attributionText: "Dicklyon / Wikimedia Commons / CC BY 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celebrity Apex",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-apex",
    file: "celebrity-apex-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Celebrity_Apex.jpg",
    author: "Jakez Bo",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Jakez Bo / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celebrity Constellation",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-constellation",
    file: "celebrity-constellation-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Celebrity_Constellation_at_Tallinn_15_July_2012.JPG",
    author: "Pjotr Mahhonin",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Pjotr Mahhonin / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celebrity Eclipse",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-eclipse",
    file: "celebrity-eclipse-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Celebrity_Eclipse_at_Circular_Quay_Sydney.jpg",
    author: "Dicklyon",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Dicklyon / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celebrity Equinox",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-equinox",
    file: "celebrity-equinox-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:MS_Celebrity_Equinox_R03.jpg",
    author: "Marc Ryckaert",
    licence: "CC BY 3.0",
    attributionRequired: true,
    attributionText: "Marc Ryckaert / Wikimedia Commons / CC BY 3.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Celebrity Infinity",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-infinity",
    file: "celebrity-infinity-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:GTS_Celebrity_Infinity.jpg",
    author: "Andrew J Bryson",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Andrew J Bryson / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celebrity Xcel",
    cruiseLine: "Celebrity Cruises",
    slug: "celebrity-xcel",
    file: "celebrity-xcel-1920.webp",
    sourceName: "Operator-supplied booking photograph",
    sourcePage: "Local asset: Celebrity_Xcel (provided for Villefranche Shore Excursions booking use)",
    author: "Provided by site operator",
    licence: "All rights reserved — used with permission for this website",
    attributionRequired: true,
    attributionText: "Celebrity Xcel photograph used with permission for Villefranche Shore Excursions",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Celestyal Discovery",
    cruiseLine: "Celestyal Cruises",
    slug: "celestyal-discovery",
    file: "celestyal-discovery-1920.webp",
    sourceName: "Operator-supplied booking photograph",
    sourcePage: "Local asset: Celestyal_Discovery (provided for Villefranche Shore Excursions booking use)",
    author: "Provided by site operator",
    licence: "All rights reserved — used with permission for this website",
    attributionRequired: true,
    attributionText: "Celestyal Discovery photograph used with permission for Villefranche Shore Excursions",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Crystal Serenity",
    cruiseLine: "Crystal Cruises",
    slug: "crystal-serenity",
    file: "crystal-serenity-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Cruise_Liner_Crystal_Serenity_(27701173480).jpg",
    author: "Rob Mitchell",
    licence: "CC BY 2.0",
    attributionRequired: true,
    attributionText: "Rob Mitchell / Wikimedia Commons / CC BY 2.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Explora I",
    cruiseLine: "Explora Journeys",
    slug: "explora-i",
    file: "explora-i-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Explora_I.jpg",
    author: "JanDragon",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "JanDragon / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Explora II",
    cruiseLine: "Explora Journeys",
    slug: "explora-ii",
    file: "explora-ii-1920.webp",
    sourceName: "Operator-supplied booking photograph",
    sourcePage: "Local asset: Explora_II (provided for Villefranche Shore Excursions booking use)",
    author: "Provided by site operator",
    licence: "All rights reserved — used with permission for this website",
    attributionRequired: true,
    attributionText: "Explora II photograph used with permission for Villefranche Shore Excursions",
    verifiedExactShip: true,
    imagePosition: "center 42%",
  },
  {
    shipName: "Explorer Of The Seas",
    cruiseLine: "Royal Caribbean Cruises",
    slug: "explorer-of-the-seas",
    file: "explorer-of-the-seas-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Explorer_of_the_Seas_(ship,_2000)_Departs_Port_Canaveral_(February_2026).jpg",
    author: "Jack Adamenko",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Jack Adamenko / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Marella Discovery",
    cruiseLine: "Marella Cruises",
    slug: "marella-discovery",
    file: "marella-discovery-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Marella_Discovery_at_Argostolion_Port_in_Greece_30.10.2025.jpg",
    author: "Littlebigenz1234",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Littlebigenz1234 / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Marella Explorer",
    cruiseLine: "Marella Cruises",
    slug: "marella-explorer",
    file: "marella-explorer-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Madeira._Funchal_cruise_ship_port._The_Marella_Explorer,_a_TUI_ship._(51859892824).jpg",
    author: "Anne and David from Kent, England UK",
    licence: "CC BY 2.0",
    attributionRequired: true,
    attributionText: "Anne and David from Kent, England UK / Wikimedia Commons / CC BY 2.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Mariner Of The Seas",
    cruiseLine: "Royal Caribbean Cruises",
    slug: "mariner-of-the-seas",
    file: "mariner-of-the-seas-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Mariner_of_the_Seas_Rhodes.jpg",
    author: "Jebulon",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Jebulon / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Norwegian Dawn",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-dawn",
    file: "norwegian-dawn-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Dawn_-_Great_Stirrup_Cay.jpg",
    author: "Stephan Bleister at de.wikipedia",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Stephan Bleister at de.wikipedia / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Norwegian Epic",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-epic",
    file: "norwegian-epic-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Epic_2017_Barcelona.jpg",
    author: "Jordiferrer",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Jordiferrer / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 42%",
  },
  {
    shipName: "Norwegian Gem",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-gem",
    file: "norwegian-gem-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Gem_bow_Pier_88_jeh.jpg",
    author: "Jim.henderson",
    licence: "CC BY-SA 3.0",
    attributionRequired: true,
    attributionText: "Jim.henderson / Wikimedia Commons / CC BY-SA 3.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Norwegian Prima",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-prima",
    file: "norwegian-prima-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Prima_in_Amsterdam_(cropped).jpg",
    author: "Chrissy85",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Chrissy85 / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Norwegian Sun",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-sun",
    file: "norwegian-sun-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Sun_at_sea_on_28_November_2006_(cropped).jpg",
    author: "Colorado Locks at English Wikipedia",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Colorado Locks at English Wikipedia / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Norwegian Viva",
    cruiseLine: "Norwegian Cruise Line",
    slug: "norwegian-viva",
    file: "norwegian-viva-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Norwegian_Viva_Mar_1_2024.jpg",
    author: "Master0Garfield",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Master0Garfield / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Oceania Vista",
    cruiseLine: "Oceania Cruises",
    slug: "oceania-vista",
    file: "oceania-vista-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Carnival_Firenze_(ex._Costa_Firenze)_(ship,_2020)_%26_Oceania_Vista_(ship,_2023)_in_Cabo_San_Lucas_(December_2025).jpg",
    author: "Jack Adamenko",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Jack Adamenko / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "55% center",
  },
  {
    shipName: "Oosterdam",
    cruiseLine: "Holland America Line",
    slug: "oosterdam",
    file: "oosterdam-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:MS_Oosterdam,_Tauranga,_2013_(04).jpg",
    author: "Bahnfrend",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Bahnfrend / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Queen Elizabeth",
    cruiseLine: "Cunard Line",
    slug: "queen-elizabeth",
    file: "queen-elizabeth-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Vancouver_(BC,_Canada),_Vancouver_Harbour,_Kreuzfahrtschiff_%22Queen_Elizabeth%22_--_2022_--_2181.jpg",
    author: "Dietmar Rabich",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Dietmar Rabich / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Queen Victoria",
    cruiseLine: "Cunard Line",
    slug: "queen-victoria",
    file: "queen-victoria-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Cruise_ship_%22Queen_Victoria%22_in_the_Solent,_England.jpg",
    author: "ITookSomePhotos",
    licence: "CC BY-SA 2.0",
    attributionRequired: true,
    attributionText: "ITookSomePhotos / Wikimedia Commons / CC BY-SA 2.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Resilient Lady",
    cruiseLine: "Virgin Voyages",
    slug: "resilient-lady",
    file: "resilient-lady-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Virgin_Voyages_Resilient_Lady_cruise_ship.jpg",
    author: "Antoloji",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Antoloji / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Royal Clipper",
    cruiseLine: "Star Clippers",
    slug: "royal-clipper",
    file: "royal-clipper-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Royal_Clipper_in_M%C3%A1laga.jpg",
    author: "Daniel Capilla",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Daniel Capilla / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Scarlet Lady",
    cruiseLine: "Virgin Voyages",
    slug: "scarlet-lady",
    file: "scarlet-lady-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Scarlet_Lady_in_Liverpool_February_2020_(cropped).jpg",
    author: "silver-novice ~ ne res adversae impediant",
    licence: "CC BY 2.0",
    attributionRequired: true,
    attributionText: "silver-novice ~ ne res adversae impediant / Wikimedia Commons / CC BY 2.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "SeaDream I",
    cruiseLine: "SeaDream Yacht Club",
    slug: "seadream-i",
    file: "seadream-i-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Seadream_1,_Barbados_-_Flickr_-_A_Guy_Named_Nyal.jpg",
    author: "A Guy Named Nyal",
    licence: "CC BY-SA 2.0",
    attributionRequired: true,
    attributionText: "A Guy Named Nyal / Wikimedia Commons / CC BY-SA 2.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "SeaDream II",
    cruiseLine: "SeaDream Yacht Club",
    slug: "seadream-ii",
    file: "seadream-ii-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:SeaDream_II_yacht.jpg",
    author: "No machine-readable author provided. Orlovic assumed (based on copyright claims).",
    licence: "CC BY-SA 3.0",
    attributionRequired: true,
    attributionText: "No machine-readable author provided. Orlovic assumed (based on copyright claims). / Wikimedia Commons / CC BY-SA 3.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Seven Seas Explorer",
    cruiseLine: "Regent Seven Seas Cruises",
    slug: "seven-seas-explorer",
    file: "seven-seas-explorer-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Seven_Seas_Explorer.jpg",
    author: "Continentaleurope",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Continentaleurope / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Seven Seas Grandeur",
    cruiseLine: "Regent Seven Seas Cruises",
    slug: "seven-seas-grandeur",
    file: "seven-seas-grandeur-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Regent_Seven_Seas_Grandeur_(53824101578).jpg",
    author: "Mustang Joe",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Mustang Joe / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Seven Seas Mariner",
    cruiseLine: "Regent Seven Seas Cruises",
    slug: "seven-seas-mariner",
    file: "seven-seas-mariner-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Seven_Seas_Mariner_Vesuvius.jpg",
    author: "Jebulon",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Jebulon / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Seven Seas Prestige",
    cruiseLine: "Regent Seven Seas Cruises",
    slug: "seven-seas-prestige",
    file: "seven-seas-prestige-1920.webp",
    sourceName: "Operator-supplied booking photograph",
    sourcePage: "Local asset: Seven_Seas_Prestige (provided for Villefranche Shore Excursions booking use)",
    author: "Provided by site operator",
    licence: "All rights reserved — used with permission for this website",
    attributionRequired: true,
    attributionText: "Seven Seas Prestige photograph used with permission for Villefranche Shore Excursions",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Silver Nova",
    cruiseLine: "Silversea Cruises",
    slug: "silver-nova",
    file: "silver-nova-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Silver_nova.jpg",
    author: "Narwhalian1",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Narwhalian1 / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Silver Shadow",
    cruiseLine: "Silversea",
    slug: "silver-shadow",
    file: "silver-shadow-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Silver_shadow_ovik01.jpg",
    author: "Petey21",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Petey21 / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 55%",
  },
  {
    shipName: "Star Clipper",
    cruiseLine: "Star Clippers",
    slug: "star-clipper",
    file: "star-clipper-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Star_Clipper_(Schiff_1992).jpg",
    author: "kansasphoto",
    licence: "CC BY 2.0",
    attributionRequired: true,
    attributionText: "kansasphoto / Wikimedia Commons / CC BY 2.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
  {
    shipName: "Star Legend",
    cruiseLine: "Windstar Cruises",
    slug: "star-legend",
    file: "star-legend-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Windstar-Cruises-Star-Legend.jpg",
    author: "David Winchester",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "David Winchester / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Valiant Lady",
    cruiseLine: "Virgin Voyages",
    slug: "valiant-lady",
    file: "valiant-lady-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Barcelone_-_ESP_-_2023.07.02_-_Virgin_Voyages_-_%C2%AB_Valiant_Lady_%C2%BB_%C2%A9_Anthony_Levrot.jpg",
    author: "Anthony Levrot",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Anthony Levrot / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Viking Jupiter",
    cruiseLine: "Viking Cruises",
    slug: "viking-jupiter",
    file: "viking-jupiter-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Viking_Jupiter_(ship,_2019).jpg",
    author: "Abxbay",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Abxbay / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Mars",
    cruiseLine: "Viking Cruises",
    slug: "viking-mars",
    file: "viking-mars-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:2022_06_Viking_Mars_(1).jpg",
    author: "Philippe Alès",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Philippe Alès / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Mira",
    cruiseLine: "Viking Cruises",
    slug: "viking-mira",
    file: "viking-mira-1920.webp",
    sourceName: "Operator-supplied booking photograph",
    sourcePage: "Local asset provided as Viking_Libra filename; hull reads Viking Mira — assigned to Mira only",
    author: "Provided by site operator",
    licence: "All rights reserved — used with permission for this website",
    attributionRequired: true,
    attributionText: "Viking Mira photograph used with permission for Villefranche Shore Excursions",
    verifiedExactShip: true,
    imagePosition: "35% center",
  },
  {
    shipName: "Viking Neptune",
    cruiseLine: "Viking Cruises",
    slug: "viking-neptune",
    file: "viking-neptune-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Viking_Neptune_at_Greenwich.jpg",
    author: "Devokewater",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Devokewater / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Saturn",
    cruiseLine: "Viking Cruises",
    slug: "viking-saturn",
    file: "viking-saturn-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Viking_Saturn,_Bergen.jpg",
    author: "Werner Wilmes",
    licence: "CC BY 2.0",
    attributionRequired: true,
    attributionText: "Werner Wilmes / Wikimedia Commons / CC BY 2.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Sea",
    cruiseLine: "Viking Cruises",
    slug: "viking-sea",
    file: "viking-sea-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Viking_Sea_at_pier_26_Port_of_Tallinn_27_May_2016.jpg",
    author: "Pjotr Mahhonin",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Pjotr Mahhonin / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Star",
    cruiseLine: "Viking Cruises",
    slug: "viking-star",
    file: "viking-star-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Cruise_ship_Viking_Star._Geirangerfjord._Norway.jpg",
    author: "Tiraspolsky",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Tiraspolsky / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Vela",
    cruiseLine: "Viking Cruises",
    slug: "viking-vela",
    file: "viking-vela-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:19_April_2025_Viking_Vela_at_Greenwich_-_08.jpg",
    author: "Jodiepedia",
    licence: "CC0",
    attributionRequired: false,
    attributionText: "Jodiepedia / Wikimedia Commons / CC0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Viking Vesta",
    cruiseLine: "Viking Cruises",
    slug: "viking-vesta",
    file: "viking-vesta-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Barcelone_-_ESP_-_2026.03.28_-_Viking_Cruises_-_%C2%AB_Viking_Vesta_%C2%BB_(vue_avant_gauche)_%C2%A9_Anthony_Levrot.jpg",
    author: "Anthony Levrot",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Anthony Levrot / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 48%",
  },
  {
    shipName: "Volendam",
    cruiseLine: "Holland America Line",
    slug: "volendam",
    file: "volendam-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:MS_Volendam_in_Juneau.JPG",
    author: "Barek",
    licence: "Public domain",
    attributionRequired: false,
    attributionText: "Barek / Wikimedia Commons / Public domain",
    verifiedExactShip: true,
    imagePosition: "center 45%",
  },
  {
    shipName: "Wind Spirit",
    cruiseLine: "Windstar Cruises",
    slug: "wind-spirit",
    file: "wind-spirit-1920.webp",
    sourceName: "Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Wind_Spirit_in_Moorea.jpg",
    author: "Windstar cruises",
    licence: "CC BY-SA 4.0",
    attributionRequired: true,
    attributionText: "Windstar cruises / Wikimedia Commons / CC BY-SA 4.0",
    verifiedExactShip: true,
    imagePosition: "center 40%",
  },
];

export function getShipImageMetadata(slug: string): ShipImageMetadata | undefined {
  return shipImageMetadataCatalog.find((entry) => entry.slug === slug);
}

export function isShipImageMetadataPublishable(meta: ShipImageMetadata): boolean {
  return (
    meta.verifiedExactShip &&
    Boolean(meta.file.trim()) &&
    Boolean(meta.sourceName.trim()) &&
    Boolean(meta.sourcePage.trim()) &&
    Boolean(meta.author.trim()) &&
    Boolean(meta.licence.trim()) &&
    Boolean(meta.attributionText.trim())
  );
}

export function listPublishableShipImageCredits(): ShipImageMetadata[] {
  return shipImageMetadataCatalog.filter(isShipImageMetadataPublishable);
}
